irc:
  server: irc.oftc.net
  nick: DorsalFunBot
  user: DorsalFunBot
  encoding: latin
  tls: False
  #tls_verify: False

channels:
- "#dorsal-fun"

modules:
  - name: lightbotactions
    class: LightbotActions
    action: light
  - name: fun
    class: Fun
    action: fun
  - name: music
    class: Music
    action: music
  - name: crazy
    class: Crazy
    action: crazy
  - name: sound
    class: Sound
  - name: cafe
    class: Cafe
    action: menu
